### ISSUE TITLE
License of the scripts

### ISSUE THREAD

**Issue by b-nairobi** [x3mSpeedy/Flow123d-python-utils#2]
I would really like to use some of your scripts, but I'd need to know the license under which they are provided to do so. Without explicit license, it will not be possible for me to use any of it at work. To quote the [GitHub guide](https://help.github.com/articles/open-source-licensing/):

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

**Comment by x3mSpeedy** [comment]
Hi, I'm glad you've shown interest in this repo. [CC-BY](https://creativecommons.org/licenses/by/4.0/) license is more than enough. So just keep my name or link to this repo somewhere in the scripts and its all good!

Since its part of other project it may not be that much transparent source code so sorry about that...

**Comment by b-nairobi** [comment]
Perfect, thanks!
